#!/usr/bin/env bash
# RLB container startup.
#
# Special modes (passed as $1):
#   wine-install   — run the Jagex Launcher installer under Wine (one-time
#                    setup for the rlb-capture image). Requires Xvfb + VNC
#                    so the operator can click through the installer GUI.
#
# Per-run env (all optional unless noted):
#   PROXY_HOST, PROXY_PORT      — enable proxy if HOST is set
#   PROXY_TYPE                  — socks5 | http   (default: socks5)
#   PROXY_USER, PROXY_PASS      — proxy auth, omit for unauthenticated
#   VNC_PORT                    — defaults to 5900 (mapped via -p on host)
#   VNC_PASSWORD                — defaults to "rlb"
#
# Recommended mounts:
#   /root/.runelite                       per-container state (named volume)
#   /root/.runelite/rlb/accounts          shared accounts (named volume,
#                                         same name across all rlb-bot
#                                         containers — see docs/docker.md)
set -euo pipefail

RL=/root/.runelite
mkdir -p "$RL"

# ---- 1. Seed public caches on a fresh volume only ----
# Existing caches are left alone so incremental updates from prior
# launches survive across container restarts.
[ -d "$RL/cache" ]      || cp -r /seed/.runelite/cache      "$RL/cache"
[ -d "$RL/jagexcache" ] || cp -r /seed/.runelite/jagexcache "$RL/jagexcache"

# ---- 2. Account state ----
# AccountLauncher manages credentials/account selection itself. The
# accounts dir is typically a shared named volume (rlb-shared-accounts)
# mounted at /root/.runelite/rlb/accounts so capture and production
# containers see the same account list.
if [ -d "$RL/rlb/accounts" ] && [ -n "$(ls -A "$RL/rlb/accounts" 2>/dev/null)" ]; then
  echo "[entrypoint] accounts dir present at $RL/rlb/accounts"
else
  echo "[entrypoint] accounts dir empty — capture via rlb-capture or" \
       "use launcher 'Add Regular' for non-Jagex accounts"
fi

# ---- 3. Optional proxy (proxychains4 wrap) ----
# proxychains4 transparently funnels every TCP connection (including the
# OSRS game protocol and RuneLite's HTTP calls) through a single proxy.
# DNS goes via the proxy too, so Jagex sees the proxy IP for everything.
PROXY_WRAP=()
if [ -n "${PROXY_HOST:-}" ]; then
  : "${PROXY_PORT:?PROXY_PORT must be set when PROXY_HOST is set}"
  PROXY_TYPE="${PROXY_TYPE:-socks5}"

  # User:pass goes inline on the proxychains "ProxyList" line.
  AUTH=""
  if [ -n "${PROXY_USER:-}" ]; then
    AUTH=" $PROXY_USER ${PROXY_PASS:-}"
  fi

  cat > /etc/proxychains4.conf <<EOF
# Generated by entrypoint.sh — do not edit by hand
strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]
$PROXY_TYPE $PROXY_HOST $PROXY_PORT$AUTH
EOF

  echo "[entrypoint] proxy enabled: $PROXY_TYPE://$PROXY_HOST:$PROXY_PORT" \
       "${PROXY_USER:+(auth: $PROXY_USER)}"
  PROXY_WRAP=(proxychains4 -q)
else
  echo "[entrypoint] no proxy configured (PROXY_HOST unset)"
fi

# ---- 3a. Special mode: wine-install ----
# One-shot: bring up Xvfb + VNC, run the Jagex Launcher installer under
# Wine, exit when the installer's wine process exits.
if [ "${1:-}" = "wine-install" ]; then
  if [ ! -f /opt/jagex/JagexLauncher.exe ]; then
    echo "ERROR: /opt/jagex/JagexLauncher.exe not present —" \
         "is this the rlb-capture image?" >&2
    exit 1
  fi
  VNC_PORT="${VNC_PORT:-5900}"
  VNC_PASSWORD="${VNC_PASSWORD:-rlb}"
  x11vnc -storepasswd "$VNC_PASSWORD" /tmp/.vncpasswd >/dev/null
  Xvfb :99 -screen 0 1280x800x24 &
  x11vnc -display :99 -rfbauth /tmp/.vncpasswd -forever -shared -rfbport "$VNC_PORT" -quiet &
  sleep 1
  echo "[entrypoint] wine-install mode — VNC on $VNC_PORT (password: $VNC_PASSWORD)"
  echo "[entrypoint] connect via VNC and click through the installer"
  exec wine /opt/jagex/JagexLauncher.exe
fi

# ---- 4. Headless display + VNC ----
# Mac's Screen Sharing app rejects "no auth" VNC, so we always set a
# password. Default is "rlb" to keep zero-config dev usable; override
# with VNC_PASSWORD for shared/exposed setups.
VNC_PORT="${VNC_PORT:-5900}"
VNC_PASSWORD="${VNC_PASSWORD:-rlb}"
x11vnc -storepasswd "$VNC_PASSWORD" /tmp/.vncpasswd >/dev/null
Xvfb :99 -screen 0 1280x800x24 &
x11vnc -display :99 -rfbauth /tmp/.vncpasswd -forever -shared -rfbport "$VNC_PORT" -quiet &
sleep 1
echo "[entrypoint] VNC on $VNC_PORT (password: $VNC_PASSWORD)"

# ---- 5. AccountLauncher ----
# The Swing pre-launcher: account list + Launch/Stop + console tail.
# It spawns RuneLite as a child process when the user clicks Launch.
# Two JVMs at runtime (launcher ~50MB + RuneLite ~600MB) — the
# launcher overhead is small relative to the bot itself.
exec "${PROXY_WRAP[@]}" java \
  --add-opens java.base/java.lang=ALL-UNNAMED \
  -cp /app/client.jar \
  net.runelite.client.launcher.AccountLauncher
